seed: 42
agent: dqn
output_dir: ./rl_outputs/tkg

# 测试参数
tests:
- load: best
  eval_prefix: best
full_tests:
- env_kwargs:
    dataset_mode: unlabeled
  test_kwargs:
    eval_prefix: unlabeled-best
    load: best

# 代理参数
agent_kwargs:
  train_steps: 2000
  save_every: 200
  eval_every: 200
  batch_size: 32
  max_grad_norm: 1.0
  lr: 0.0003
  weight_decay: 0.001
  network_params:
    dropout: 0.2
    hidden_dim: 256
  val_rounds: 5
  target_update_every: 100
  optimization_steps_per_train_step: 8
  replay_memory_size: 20000
  offline_steps: 500
  cql_loss_weight: 0.1
  output_dir: ./rl_outputs/tkg
  
# 环境参数
env: tkg
env_kwargs:
  max_steps: 5
  reward_scale: 10.0
  state_repr:
  - sample_features
  - query_features
  - similarity
  - history
  - curr_step

# 在线学习参数
online_learning:
  enabled: true
  update_frequency: 10
  optimization_steps: 5
  min_experiences: 32
  exploration_ratio: 0.1

# 训练参数
training:
  pretrain_ratio: 0.3  # 预训练占总训练的比例
  eval_interval: 50    # 每多少步评估一次
